In [1311]:
# Importing libraries 
import pandas as pd 
import numpy as np
import tensorflow as tf
from pathlib import Path
import os

In [1312]:
place = str (Path(os.getcwd()).parent) + '\\data\\data.csv' # finding database
data = pd.read_csv(place, sep='\t')                  # opening database

In [1313]:
data.head(100)                                       # showing first 100 rows

Q1A  Q1I   Q1E  Q2A  Q2I   Q2E  Q3A  Q3I   Q3E  Q4A  ...   Q91E  country  \
0     5   51  7107    3   91  2522    1   56  6180    2  ...   4609       US   
1     5   39  6354    5   13  3092    1   12  5243    5  ...  10409       AU   
2     3   17  5397    4   35  2747    5   40  5262    3  ...   2691       BR   
3     5   41  3055    2   14  3348    1   13  5141    1  ...   3697       CZ   
4     1   76  2542    2   54  1878    1   15  5637    1  ...   1662       CA   
..  ...  ...   ...  ...  ...   ...  ...  ...   ...  ...  ...    ...      ...   
95    2   51  5755    1   68  2571    4   61  7700    5  ...   4088       US   
96    5    4  4023    5   79  2561    5   60  5478    5  ...   5587       PE   
97    2   83  2076    5   91  1767    2   71  5729    4  ...   2458       AU   
98    4    4  4503    3   51  2259    4    7  4742    5  ...   3943       US   
99    3   29  3133    2   89  2085    5   35  3166    3  ...   2748       US   

               dateload  introelapse  testelapse  surveyelapse  gender  \
0   2019-02-20 17:35:52            1         461            16       2   
1   2019-02-20 17:46:32           21         467            15       1   
2   2019-02-20 18:10:24           56         306            17       1   
3   2019-02-20 18:16:21            2         287            14       1   
4   2019-02-20 18:21:49            2         325            12       1   
..                  ...          ...         ...           ...     ...   
95  2019-02-22 06:49:53            2         367            14       1   
96  2019-02-22 07:29:19            3         395            23       2   
97  2019-02-22 07:29:54          587         419            18       1   
98  2019-02-22 08:06:18            4         300            77       2   
99  2019-02-22 08:44:05            2         386            18       2   

    engnat  age  IE  
0        1   23   3  
1        2   25   2  
2        2   19   1  
3        1   23   1  
4        1   18   2  
..     ...  ...  ..  
95       1   25   1  
96       2   29   1  
97       1   19   1  
98       1   38   3  
99       1   29   3  

[100 rows x 282 columns]

In [1314]:
data.describe()                                     # showing statistics

Q1A          Q1I           Q1E          Q2A          Q2I  \
count  7188.000000  7188.000000  7.188000e+03  7188.000000  7188.000000   
mean      3.716055    45.990818  1.232196e+04     3.428492    45.722593   
std       1.488674    26.271732  5.754300e+05     1.478393    26.609030   
min       1.000000     1.000000  5.330000e+02     1.000000     1.000000   
25%       2.000000    23.000000  2.992000e+03     2.000000    22.000000   
50%       4.000000    45.000000  3.912500e+03     4.000000    45.000000   
75%       5.000000    69.000000  5.285000e+03     5.000000    69.000000   
max       5.000000    91.000000  4.876287e+07     5.000000    91.000000   

                Q2E          Q3A          Q3I           Q3E          Q4A  ...  \
count  7.188000e+03  7188.000000  7188.000000  7.188000e+03  7188.000000  ...   
mean   1.886704e+04     3.458125    45.902476  1.830787e+04     3.166388  ...   
std    9.836502e+05     1.512086    26.115185  1.014611e+06     1.507506  ...   
min    5.000000e+02     1.000000     1.000000  5.070000e+02     1.000000  ...   
25%    2.366750e+03     2.000000    23.000000  3.426000e+03     2.000000  ...   
50%    3.100000e+03     4.000000    46.000000  4.605500e+03     3.000000  ...   
75%    4.265250e+03     5.000000    69.000000  6.433750e+03     5.000000  ...   
max    8.050821e+07     5.000000    91.000000  8.601586e+07     5.000000  ...   

              Q91A         Q91I          Q91E   introelapse    testelapse  \
count  7188.000000  7188.000000  7.188000e+03  7.188000e+03  7.188000e+03   
mean      2.391208    45.521842  5.617112e+03  1.563320e+03  1.516260e+03   
std       1.443135    26.174255  4.089489e+04  3.103143e+04  2.526853e+04   
min       1.000000     1.000000  5.130000e+02  1.000000e+00  1.480000e+02   
25%       1.000000    23.000000  2.539750e+03  3.000000e+00  3.050000e+02   
50%       2.000000    45.000000  3.410000e+03  7.000000e+00  3.820000e+02   
75%       4.000000    68.000000  4.805000e+03  3.600000e+01  5.080000e+02   
max       5.000000    91.000000  3.053623e+06  1.902817e+06  1.405436e+06   

       surveyelapse       gender       engnat           age           IE  
count  7.188000e+03  7188.000000  7188.000000  7.188000e+03  7188.000000  
mean   2.903364e+03     1.623678     1.306483  1.235132e+03     1.626461  
std    9.832530e+04     0.562876     0.465868  1.023245e+05     0.856315  
min    2.000000e+00     0.000000     0.000000  1.400000e+01     0.000000  
25%    1.400000e+01     1.000000     1.000000  1.800000e+01     1.000000  
50%    1.800000e+01     2.000000     1.000000  2.200000e+01     1.000000  
75%    2.400000e+01     2.000000     2.000000  3.000000e+01     2.000000  
max    6.376603e+06     3.000000     2.000000  8.675309e+06     3.000000  

[8 rows x 280 columns]

In [1315]:
# Copy of database
df = data.copy()
data.shape


(7188, 282)

In [1316]:
data.head()

Q1A  Q1I   Q1E  Q2A  Q2I   Q2E  Q3A  Q3I   Q3E  Q4A  ...   Q91E  country  \
0    5   51  7107    3   91  2522    1   56  6180    2  ...   4609       US   
1    5   39  6354    5   13  3092    1   12  5243    5  ...  10409       AU   
2    3   17  5397    4   35  2747    5   40  5262    3  ...   2691       BR   
3    5   41  3055    2   14  3348    1   13  5141    1  ...   3697       CZ   
4    1   76  2542    2   54  1878    1   15  5637    1  ...   1662       CA   

              dateload  introelapse  testelapse  surveyelapse  gender  engnat  \
0  2019-02-20 17:35:52            1         461            16       2       1   
1  2019-02-20 17:46:32           21         467            15       1       2   
2  2019-02-20 18:10:24           56         306            17       1       2   
3  2019-02-20 18:16:21            2         287            14       1       1   
4  2019-02-20 18:21:49            2         325            12       1       1   

   age  IE  
0   23   3  
1   25   2  
2   19   1  
3   23   1  
4   18   2  

[5 rows x 282 columns]

In [1317]:
data['gender'].value_counts()

2    4175
1    2718
3     201
0      94
Name: gender, dtype: int64

In [1318]:
data['IE'].value_counts()

1    4404
3    1769
2     990
0      25
Name: IE, dtype: int64

In [1319]:
filt = ~( (df['IE'] == 0 ) | (df['IE'] == 3) | (df['gender'] == 0) )

In [1320]:
# Removing rows with values 0 and 3 in column IE 
df = df[filt]

In [1321]:
df.head()

Q1A  Q1I   Q1E  Q2A  Q2I   Q2E  Q3A  Q3I   Q3E  Q4A  ...   Q91E  country  \
1    5   39  6354    5   13  3092    1   12  5243    5  ...  10409       AU   
2    3   17  5397    4   35  2747    5   40  5262    3  ...   2691       BR   
3    5   41  3055    2   14  3348    1   13  5141    1  ...   3697       CZ   
4    1   76  2542    2   54  1878    1   15  5637    1  ...   1662       CA   
5    2   77  1455    5   75  1864    5   34  5235    1  ...   5858       US   

              dateload  introelapse  testelapse  surveyelapse  gender  engnat  \
1  2019-02-20 17:46:32           21         467            15       1       2   
2  2019-02-20 18:10:24           56         306            17       1       2   
3  2019-02-20 18:16:21            2         287            14       1       1   
4  2019-02-20 18:21:49            2         325            12       1       1   
5  2019-02-20 19:22:54            6         596            10       1       1   

   age  IE  
1   25   2  
2   19   1  
3   23   1  
4   18   2  
5   22   1  

[5 rows x 282 columns]

In [1322]:
df['IE'].value_counts()

1    4354
2     969
Name: IE, dtype: int64

In [1323]:
df['gender'].value_counts()

2    3102
1    2078
3     143
Name: gender, dtype: int64

In [1324]:
df.shape

(5323, 282)

In [1325]:
df.drop(['dateload'], axis=1, inplace=True)

In [1326]:
df.head()

Q1A  Q1I   Q1E  Q2A  Q2I   Q2E  Q3A  Q3I   Q3E  Q4A  ...  Q91I   Q91E  \
1    5   39  6354    5   13  3092    1   12  5243    5  ...     1  10409   
2    3   17  5397    4   35  2747    5   40  5262    3  ...    19   2691   
3    5   41  3055    2   14  3348    1   13  5141    1  ...    23   3697   
4    1   76  2542    2   54  1878    1   15  5637    1  ...    69   1662   
5    2   77  1455    5   75  1864    5   34  5235    1  ...    62   5858   

   country  introelapse  testelapse  surveyelapse  gender  engnat  age  IE  
1       AU           21         467            15       1       2   25   2  
2       BR           56         306            17       1       2   19   1  
3       CZ            2         287            14       1       1   23   1  
4       CA            2         325            12       1       1   18   2  
5       US            6         596            10       1       1   22   1  

[5 rows x 281 columns]

In [1327]:
df.memory_usage(deep = True)

Index           42584
Q1A             42584
Q1I             42584
Q1E             42584
Q2A             42584
                ...  
surveyelapse    42584
gender          42584
engnat          42584
age             42584
IE              42584
Length: 282, dtype: int64

In [1328]:
df.dtypes.value_counts()

int64     280
object      1
dtype: int64

In [1329]:
columns = df.columns
columns

Index(['Q1A', 'Q1I', 'Q1E', 'Q2A', 'Q2I', 'Q2E', 'Q3A', 'Q3I', 'Q3E', 'Q4A',
       ...
       'Q91I', 'Q91E', 'country', 'introelapse', 'testelapse', 'surveyelapse',
       'gender', 'engnat', 'age', 'IE'],
      dtype='object', length=281)

In [1330]:
intcolumns = columns.drop('country')

In [1331]:
intcolumns

Index(['Q1A', 'Q1I', 'Q1E', 'Q2A', 'Q2I', 'Q2E', 'Q3A', 'Q3I', 'Q3E', 'Q4A',
       ...
       'Q91A', 'Q91I', 'Q91E', 'introelapse', 'testelapse', 'surveyelapse',
       'gender', 'engnat', 'age', 'IE'],
      dtype='object', length=280)

In [1332]:
data.memory_usage(deep = True)

Index             128
Q1A             57504
Q1I             57504
Q1E             57504
Q2A             57504
                ...  
surveyelapse    57504
gender          57504
engnat          57504
age             57504
IE              57504
Length: 283, dtype: int64

In [1333]:
df[intcolumns] = df[intcolumns].astype(np.int8)
df['country'] = df['country'].astype('category')

In [1334]:
df.memory_usage(deep = True)

Index           42584
Q1A              5323
Q1I              5323
Q1E              5323
Q2A              5323
                ...  
surveyelapse     5323
gender           5323
engnat           5323
age              5323
IE               5323
Length: 282, dtype: int64

In [1335]:
df.memory_usage(deep = True)/data[intcolumns].memory_usage(deep = True)

IE                0.092567
Index           332.687500
Q10A              0.092567
Q10E              0.092567
Q10I              0.092567
                   ...    
engnat            0.092567
gender            0.092567
introelapse       0.092567
surveyelapse      0.092567
testelapse        0.092567
Length: 282, dtype: float64

In [1336]:
# Label Encoding the "country" and "IE" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['country'] = le.fit_transform(df['country'].values)
df['IE'] = le.fit_transform(df['IE'].values)


In [1337]:
df['IE']

1       1
2       0
3       0
4       1
5       0
       ..
7183    0
7184    0
7185    0
7186    0
7187    0
Name: IE, Length: 5323, dtype: int64

In [1338]:
df.columns

Index(['Q1A', 'Q1I', 'Q1E', 'Q2A', 'Q2I', 'Q2E', 'Q3A', 'Q3I', 'Q3E', 'Q4A',
       ...
       'Q91I', 'Q91E', 'country', 'introelapse', 'testelapse', 'surveyelapse',
       'gender', 'engnat', 'age', 'IE'],
      dtype='object', length=281)

In [1339]:
df.head()

Q1A  Q1I  Q1E  Q2A  Q2I  Q2E  Q3A  Q3I  Q3E  Q4A  ...  Q91I  Q91E  country  \
1    5   39  -46    5   13   20    1   12  123    5  ...     1   -87        6   
2    3   17   21    4   35  -69    5   40 -114    3  ...    19  -125       14   
3    5   41  -17    2   14   20    1   13   21    1  ...    23   113       24   
4    1   76  -18    2   54   86    1   15    5    1  ...    69   126       17   
5    2   77  -81    5   75   72    5   34  115    1  ...    62   -30      108   

   introelapse  testelapse  surveyelapse  gender  engnat  age  IE  
1           21         -45            15       1       2   25   1  
2           56          50            17       1       2   19   0  
3            2          31            14       1       1   23   0  
4            2          69            12       1       1   18   1  
5            6          84            10       1       1   22   0  

[5 rows x 281 columns]

In [1340]:
X = df.iloc[:, 0:280].values        # all columns except the last one
y = df.iloc[:,280].values           # getting the last column(target)

In [1341]:
print("X >>\n",X)
print("y >>\n",y)

X >>
 [[   5   39  -46 ...    1    2   25]
 [   3   17   21 ...    1    2   19]
 [   5   41  -17 ...    1    1   23]
 ...
 [   3   29  -38 ...    2    2   28]
 [   4   15 -127 ...    2    1   19]
 [   5   57 -122 ...    2    1   25]]
y >>
 [1 0 0 ... 0 0 0]


In [1342]:
# Splitting the data into training and test sets

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0) # random_state define the order of collecting data

In [1343]:
# Feature Scaling

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()                            # Adjusting the data to be in the same scale
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [1344]:
print("X_train >>\n",X_train,
      "\nX_test >>\n",X_test)

X_train >>
 [[-1.90397584  0.83617006  0.01460497 ... -1.19829693  1.47572684
  -0.51535851]
 [ 0.81699383 -1.60304267 -0.10802687 ...  0.66796069 -0.66739897
  -0.76694216]
 [ 0.81699383  1.21729705  1.41805823 ... -1.19829693 -0.66739897
   0.23939247]
 ...
 [-1.22373342 -1.06946489 -1.63411196 ...  0.66796069  1.47572684
   0.32325368]
 [-0.54349101  0.72183196 -0.74843758 ...  0.66796069  1.47572684
  -0.85080338]
 [-1.22373342  0.34070497  0.91390512 ...  0.66796069 -0.66739897
  -0.76694216]] 
X_test >>
 [[-0.54349101 -0.11664741  1.49981279 ...  0.66796069 -0.66739897
  -0.51535851]
 [ 0.81699383 -0.15476011 -0.72118606 ...  0.66796069 -0.66739897
  -0.68308094]
 [ 0.81699383  1.44597324  0.6141384  ...  0.66796069 -0.66739897
   0.74255978]
 ...
 [ 0.13675141 -0.26909821 -0.42141934 ... -1.19829693 -0.66739897
  -0.51535851]
 [ 0.81699383  0.41693037 -0.20340719 ... -1.19829693 -0.66739897
  -0.51535851]
 [ 0.81699383  1.25540975  1.45893551 ... -1.19829693 -0.66739897
   3.258

In [1345]:
print(np.shape(X),'\n',np.shape(X_train),'\n',np.shape(X_test))

(5323, 280) 
 (4258, 280) 
 (1065, 280)


In [1346]:
# Building the ANN

ann = tf.keras.models.Sequential()

In [1347]:
ann.add(tf.keras.layers.Dense(units=140, activation='relu')) # Adding the first hidden layer

In [1348]:
ann.add(tf.keras.layers.Dense(units=70, activation='relu')) # Adding the second hidden layer

In [1349]:
ann.add(tf.keras.layers.Dense(units=35, activation='relu')) # adding the third hidden layer

In [1350]:
ann.add(tf.keras.layers.Dense(units=5, activation='relu')) # Adding the fourth hidden layer

In [1351]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [1352]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [1353]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 50)

Epoch 1/50
134/134 [==============================] - 2s 4ms/step - loss: 0.2200 - accuracy: 0.9110
Epoch 2/50
134/134 [==============================] - 0s 3ms/step - loss: 0.1160 - accuracy: 0.9570
Epoch 3/50
134/134 [==============================] - 0s 4ms/step - loss: 0.0633 - accuracy: 0.9824
Epoch 4/50
134/134 [==============================] - 1s 4ms/step - loss: 0.0340 - accuracy: 0.9915
Epoch 5/50
134/134 [==============================] - 0s 3ms/step - loss: 0.0194 - accuracy: 0.9937
Epoch 6/50
134/134 [==============================] - 0s 3ms/step - loss: 0.0080 - accuracy: 0.9979
Epoch 7/50
134/134 [==============================] - 0s 3ms/step - loss: 0.0024 - accuracy: 0.9993
Epoch 8/50
134/134 [==============================] - 0s 3ms/step - loss: 8.7120e-04 - accuracy: 1.0000
Epoch 9/50
134/134 [==============================] - 0s 3ms/step - loss: 4.7334e-04 - accuracy: 1.0000: 0s - loss: 4.7458e-04 - accuracy: 1.00
Epoch 10/50
134/134 [==============================]

In [1354]:
# Predicting the Test set results
y_pred = ann.predict(X_test)
y_pred

array([[5.4014879e-01],
       [1.2199949e-19],
       [9.6195230e-10],
       ...,
       [4.6018309e-09],
       [2.0553415e-11],
       [5.2823124e-11]], dtype=float32)

In [1355]:
y_pred  = (y_pred > 0.5)
y_pred

array([[ True],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [1356]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm) # ACCURACY IN ~= 93% \O/

[[846  31]
 [ 43 145]]


In [1357]:
total = sum(sum(cm))
total

1065

In [1358]:
erro = cm[0,1] + cm[1,0]
erro

74

In [1359]:

accuracy = ((erro*(-100))/total)+100
accuracy

93.05164319248826